name: cicd_pipeline

on: push 

jobs: 
  job-1: 
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: run python script
        run: python hello.py

  job-2:
    name: Build
    runs-on: ubuntu-latest
    needs: [job-1]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.2.2
      - name: create artifact
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: final artifact
          path: .

      
